filebeat.inputs:
  # - type: filestream
  #   id: suricata-logs
  #   paths:
  #     - /var/log/suricata/eve.json  # Путь внутри контейнера Filebeat (проброшенный volume из Suricata)
  #   json.keys_under_root: true      # Говорим, что это JSON
  #   json.add_error_key: true
  #   fields:
  #     suricata_source: suricata
  #   fields_under_root: false
  - type: log
    enabled: true
    paths:
      - /var/log/suricata/eve.json
    json.keys_under_root: true          # put all the JSON keys at the top level
    json.add_error_key: true            # in case a line isn’t valid JSON
    json.overwrite_keys: true

processors:
  - decode_json_fields:
      fields: ["message"]
      target: ""
      overwrite_keys: true
      add_error_key: true


output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "suricata-%{+yyyy.MM.dd}"
  #pipeline: "suricata-geoip"

setup.ilm.enabled: false

logging.to_files: false
logging.to_stdout: true
logging.level: info

# ---------------------------------
# Template settings
# ---------------------------------
setup.template.name: "suricata"
setup.template.pattern: "suricata-*"