apiVersion: 1

datasources:
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    isDefault: true
    jsonData:
      esVersion: 8.0.0
      timeField: "@timestamp"
    version: 1
    editable: false
